POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Derek Carlson",
    "dateOfBirth": "1986-07-09",
    "ssn": "050555-999s",
    "gender": "male",
    "occupation": "Freeroamer"
}